### ISSUE TITLE
在新创建项目需要安装时，点击接受之后会变成这样，代码没改变

### ISSUE THREAD

**Issue by lvlongfei666** [xzncit/A3Mall#45]
![image](https://user-images.githubusercontent.com/43194847/219941182-29e23bdf-07ce-48c6-96d5-c668a9779847.png)
![image](https://user-images.githubusercontent.com/43194847/219941189-7ced9ea7-4045-40ab-89d0-0d192c84a94d.png)

**Comment by xzncit** [comment]
需要配置伪静态的，安装地址：域名/install
